# Generated by Django 3.0.7 on 2020-06-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indow_apis', '0002_remove_instagramprofile_app_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramusermedia',
            name='id',
        ),
        migrations.AlterField(
            model_name='instagramusermedia',
            name='media_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
