# Generated by Django 3.0.7 on 2020-06-20 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indow_apis', '0004_auto_20200620_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrammediainsight',
            name='insta_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indow_apis.InstagramProfile'),
        ),
        migrations.AlterField(
            model_name='instagramusermedia',
            name='insta_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indow_apis.InstagramProfile'),
        ),
    ]
