# Generated by Django 3.0.7 on 2020-06-20 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indow_apis', '0005_auto_20200620_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrammediacomments',
            name='media',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='indow_apis.InstagramUserMedia'),
        ),
    ]
