# Generated by Django 3.0.7 on 2020-06-20 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indow_apis', '0006_auto_20200620_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagrammediacomments',
            name='media',
        ),
        migrations.AddField(
            model_name='instagrammediacomments',
            name='media_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='indow_apis.InstagramUserMedia'),
        ),
    ]
