# Generated by Django 3.0.7 on 2020-06-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indow_apis', '0007_auto_20200620_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagrammediacomments',
            old_name='media_id',
            new_name='media',
        ),
    ]
